### ISSUE TITLE
enumerable/entries implicit 

### ISSUE THREAD

**Issue by jamOne-** [marcinnajder/powerseq#3]
Hey!
I would like to add implicit typing of values (`TValue`) in `entries` function.
And also I wonder why arrays are handled in other way, wouldn't just using `Object.keys` be sufficient?

**Comment by marcinnajder** [comment]
Hey! :)

There are few differences between `Object.keys` and `array.keys`:
- first returns strings, second returns numbers
- first returns array, second returns iterable
- for sparse arrays, first returns only existing keys, second returns all indexes until the length of the array

I wanted to keep the semantics of `array.entries()`. Thank you for comment!
marcin
